Make passthroughEvent and passthroughEventAsync for passin Sync and a…
SevInf/qemitter pull request #3
Opened 2017-01-30 16:03 UTC by up73k

…sync events.

2017-01-31 18:15 UTC, DudaGod requested changes

2017-01-31 18:15 UTC, DudaGod commented on utils.js
> +exports.passthroughEventAsync = passthroughEventAsync;
у тебя сейчас порядок объявлений не соответствует порядку экспорта. Это не ошибка, но кажется проще читается если сначала объявить синхронную функцию, а потом асинхронную.

2017-01-31 18:15 UTC, DudaGod commented on utils.js
> +    event.forEach((event) => passthroughEvent(from, to, event));
если тут стрелочную используешь, то почему бы и всю функцию `passthroughEvent` не объявить через стрелочную функцию?

2017-01-31 18:15 UTC, DudaGod commented on test/utils.js
> +    });
опять же эта не ошибка, но мне почему то больше нравится когда сначала описываются тесты на синхронную функцию, а затем на асинхронную.

2017-01-31 18:15 UTC, DudaGod commented on test/utils.js
> +    });
предлагаю еще на es6 переписать

2017-01-31 18:15 UTC, DudaGod commented on test/utils.js
> +                setTimeout(firstEventHandler(), 100);
сейчас шпион вызывается не дожидаясь когда таймер закончится

2017-01-31 18:15 UTC, DudaGod commented on test/utils.js
> +        });
эти два теста очень похожи на те, что выше. Может стоит их тогда в массив загнать?

2017-02-01 12:33 UTC, DudaGod requested changes

2017-02-01 12:33 UTC, DudaGod commented on test/utils.js
>  describe('QEmitter/utils', function() {
у тебя над describe-ом остались `var`-ы

2017-02-01 12:33 UTC, DudaGod commented on test/utils.js
>          it('should passthrough event', function() {
обычно при переписывании на es6 мы вместо `function` юзаем стрелочную функцию

2017-02-01 12:33 UTC, DudaGod commented on test/utils.js
> +        it('should synchrony call event handlers (not in nexTick)', function() {
`should call event handlers synchronously`. Кажется итак понятно, что в nextTick-и они не полетят

2017-02-01 12:33 UTC, DudaGod commented on test/utils.js
> +             utils.passthroughEvent(from, to, 'some-event');
пробел лишний и давай этот вызов отобьем пустой строкой от объявления переменных

2017-02-01 12:33 UTC, DudaGod commented on test/utils.js
> +            return assert.equal(flag, 1);
а зачем тут `return`?

2017-02-01 12:33 UTC, DudaGod commented on test/utils.js
>                  spy = sinon.spy();
остались `var`-ы и ниже тоже.
Обычно при переписывании на es6, переписывается весь файл

2017-02-01 14:09 UTC, DudaGod commented on index.js
>      }));
кажется тут можно в одну строку

2017-02-01 14:09 UTC, DudaGod commented on index.js
>  };
давай тогда и `QEmitter` на класс перепишем если ты начал этот файл на es6 переписывать

2017-02-01 14:09 UTC, DudaGod commented on test/utils.js
> +        it('should synchrony call event handlers (not in nexTick)', () => {
предлагаю все таки перефразировать этот `it`

2017-02-01 14:29 UTC, DudaGod commented on test/utils.js
>              utils.passthroughEvent(from, to, 'some-event');
отбей пустой строкой

2017-02-01 14:29 UTC, DudaGod commented on test/utils.js
>                      assert.callOrder(insideHandler, afterWait);
кажется это можно в 1 строку

2017-02-01 14:31 UTC, DudaGod commented
в остальном /ok
Незабудь сосквошить и проверить интеграционно.

2017-02-03 10:23 UTC, eGavr reviewed
Избавься от копипасты, поправь один тест + еще пару замечаний и призывай снова.

2017-02-03 10:23 UTC, eGavr commented on index.js
> +    constructor() {
не нужно здесь конструктор звать

2017-02-03 10:23 UTC, eGavr commented on index.js
> +        const args = Array.prototype.slice.call(arguments, 1);
может так сделать?

```js
const args = _(arguments).values().tail().value()
```

кажется, что так сразу понятно, что происходит.

2017-02-03 10:23 UTC, eGavr commented on utils.js
> +};
```js
const magic = (methodName) => {
    const passEvents = (from, to, event) => {
        if (typeof event === 'string') {
            from.on(event, to[methodName].bind(to, event));
            return;
        }
        event.forEach((event) => passEvents(from, to, event));
    };

    return passEvents;
};


exports.passthroughEvent = magic('emit');
exports.passthroughEventAsync = magic('emitAndWait');
```

2017-02-03 10:23 UTC, eGavr commented on test/utils.js
> +        });
немного не так подобные тесты лучше писать :) давай так:

```js
it('should call event handlers synchronously', () => {
    const from = new QEmitter();
    const to = new QEmitter();
    const handler = sinon.spy();

    utils.passthroughEvent(from, to, 'some-event');

    to.on('some-event', handler)
    from.emit('some-event', 'some-arg');

    assert.calledOnce(handler);
    assert.calledWith(handler, 'some-arg');
});
```

2017-02-03 10:23 UTC, eGavr commented on test/utils.js
> +            utils.passthroughEventAsync(from, to, 'some-event');
после `utils.pass..`

пустую строчку

а `to.on('some-event', spy);` и `from.emit('some-event', 'val1', 'val2');` разделять пустой строкой не надо.

2017-02-03 10:23 UTC, eGavr commented on test/utils.js
>                  return Q.delay(100)
достаточно указать `Q.delay(1)`  :) ну 100 миллисекунд реально долго же)

2017-02-06 14:31 UTC, up73k commented on test/utils.js
> +        });
решил удалить этот тест, тк он по смыслу дублирует первый: когда сломается синхронность проброса событий (например, поменяется на асинхронность), то сломается и первый тест.

2017-02-07 09:40 UTC, DudaGod commented on index.js
лишняя пустая строка

2017-02-07 09:43 UTC, DudaGod commented on index.js
> +class QEmitter extends EventEmitter {
```js
module.exports = class QEmitter extends EventEmitter {...}
```
и не нужно будет внизу экспортить

2017-02-07 09:45 UTC, DudaGod commented on package.json
> +  "description": " ",
какое то странное описание =)
Сюда можешь написать что-то из доки. Например - `Node.js event emitter with promises support`

2017-02-07 09:46 UTC, DudaGod commented on test/utils.js
> +const Q = require('q');
обычно внешние зависимости указываем первыми, а затем внутренние.

2017-02-07 09:51 UTC, DudaGod commented on test/utils.js
> +            utils.passthroughEventAsync(from, to, ['some-event', 'other-event']);
выше ты эту строку отбил пустыми строками сверху и снизу.

2017-02-07 09:54 UTC, DudaGod reviewed
_

2017-02-07 15:55 UTC, eGavr approved these changes
/ok

Но не забудь, что изменения мажорные

2017-02-07 15:55 UTC, eGavr commented on utils.js
> +exports.passthroughEvent = mkPassthroughEvent('emit');
mkPassthroughFn

2017-02-07 15:55 UTC, eGavr commented on utils.js
> +exports.passthroughEventAsync = mkPassthroughEvent('emitAndWait');
mkPassthroughFn

2017-02-07 15:55 UTC, eGavr commented on test/utils.js
> +            assert.calledWith(spy, 'val1', 'val2');
еще один ассерт перед этим:

```js
assert.calledOnce(spy);
```

2017-02-07 15:55 UTC, eGavr commented on test/utils.js
>              });
а че не в одну строчку?

2017-02-09 20:29 UTC, j0tunn commented
что с PR'ом, почему не вливаем? @DudaGod от тебя крестик стоит, что-то еще нужно поправить?

2017-02-09 21:14 UTC, DudaGod approved these changes

2017-02-09 21:16 UTC, DudaGod commented
заапрувил. Я предложил вливать вместе с гермионой для которой этот PR делался.

2017-02-13 08:38 UTC, merged